package com.trm.coinvision.core.network.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ValueInCurrency(
  @SerialName("aed") val aed: Double?,
  @SerialName("ars") val ars: Double?,
  @SerialName("aud") val aud: Double?,
  @SerialName("bch") val bch: Double?,
  @SerialName("bdt") val bdt: Double?,
  @SerialName("bhd") val bhd: Double?,
  @SerialName("bits") val bits: Double?,
  @SerialName("bmd") val bmd: Double?,
  @SerialName("bnb") val bnb: Double?,
  @SerialName("brl") val brl: Double?,
  @SerialName("btc") val btc: Double?,
  @SerialName("cad") val cad: Double?,
  @SerialName("chf") val chf: Double?,
  @SerialName("clp") val clp: Double?,
  @SerialName("cny") val cny: Double?,
  @SerialName("czk") val czk: Double?,
  @SerialName("dkk") val dkk: Double?,
  @SerialName("dot") val dot: Double?,
  @SerialName("eos") val eos: Double?,
  @SerialName("eth") val eth: Double?,
  @SerialName("eur") val eur: Double?,
  @SerialName("gbp") val gbp: Double?,
  @SerialName("hkd") val hkd: Double?,
  @SerialName("huf") val huf: Double?,
  @SerialName("idr") val idr: Double?,
  @SerialName("ils") val ils: Double?,
  @SerialName("inr") val inr: Double?,
  @SerialName("jpy") val jpy: Double?,
  @SerialName("krw") val krw: Double?,
  @SerialName("kwd") val kwd: Double?,
  @SerialName("link") val link: Double?,
  @SerialName("lkr") val lkr: Double?,
  @SerialName("ltc") val ltc: Double?,
  @SerialName("mmk") val mmk: Double?,
  @SerialName("mxn") val mxn: Double?,
  @SerialName("myr") val myr: Double?,
  @SerialName("ngn") val ngn: Double?,
  @SerialName("nok") val nok: Double?,
  @SerialName("nzd") val nzd: Double?,
  @SerialName("php") val php: Double?,
  @SerialName("pkr") val pkr: Double?,
  @SerialName("pln") val pln: Double?,
  @SerialName("rub") val rub: Double?,
  @SerialName("sar") val sar: Double?,
  @SerialName("sats") val sats: Double?,
  @SerialName("sek") val sek: Double?,
  @SerialName("sgd") val sgd: Double?,
  @SerialName("thb") val thb: Double?,
  @SerialName("try") val tryX: Double?,
  @SerialName("twd") val twd: Double?,
  @SerialName("uah") val uah: Double?,
  @SerialName("usd") val usd: Double?,
  @SerialName("vef") val vef: Double?,
  @SerialName("vnd") val vnd: Double?,
  @SerialName("xag") val xag: Double?,
  @SerialName("xau") val xau: Double?,
  @SerialName("xdr") val xdr: Double?,
  @SerialName("xlm") val xlm: Double?,
  @SerialName("xrp") val xrp: Double?,
  @SerialName("yfi") val yfi: Double?,
  @SerialName("zar") val zar: Double?
)
