package com.trm.coinvision.core.network.model

import com.trm.coinvision.core.domain.model.ValueInCurrencyDTO
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
internal data class ValueInCurrency(
  @SerialName("aed") override val aed: Double?,
  @SerialName("ars") override val ars: Double?,
  @SerialName("aud") override val aud: Double?,
  @SerialName("bch") override val bch: Double?,
  @SerialName("bdt") override val bdt: Double?,
  @SerialName("bhd") override val bhd: Double?,
  @SerialName("bits") override val bits: Double?,
  @SerialName("bmd") override val bmd: Double?,
  @SerialName("bnb") override val bnb: Double?,
  @SerialName("brl") override val brl: Double?,
  @SerialName("btc") override val btc: Double?,
  @SerialName("cad") override val cad: Double?,
  @SerialName("chf") override val chf: Double?,
  @SerialName("clp") override val clp: Double?,
  @SerialName("cny") override val cny: Double?,
  @SerialName("czk") override val czk: Double?,
  @SerialName("dkk") override val dkk: Double?,
  @SerialName("dot") override val dot: Double?,
  @SerialName("eos") override val eos: Double?,
  @SerialName("eth") override val eth: Double?,
  @SerialName("eur") override val eur: Double?,
  @SerialName("gbp") override val gbp: Double?,
  @SerialName("hkd") override val hkd: Double?,
  @SerialName("huf") override val huf: Double?,
  @SerialName("idr") override val idr: Double?,
  @SerialName("ils") override val ils: Double?,
  @SerialName("inr") override val inr: Double?,
  @SerialName("jpy") override val jpy: Double?,
  @SerialName("krw") override val krw: Double?,
  @SerialName("kwd") override val kwd: Double?,
  @SerialName("link") override val link: Double?,
  @SerialName("lkr") override val lkr: Double?,
  @SerialName("ltc") override val ltc: Double?,
  @SerialName("mmk") override val mmk: Double?,
  @SerialName("mxn") override val mxn: Double?,
  @SerialName("myr") override val myr: Double?,
  @SerialName("ngn") override val ngn: Double?,
  @SerialName("nok") override val nok: Double?,
  @SerialName("nzd") override val nzd: Double?,
  @SerialName("php") override val php: Double?,
  @SerialName("pkr") override val pkr: Double?,
  @SerialName("pln") override val pln: Double?,
  @SerialName("rub") override val rub: Double?,
  @SerialName("sar") override val sar: Double?,
  @SerialName("sats") override val sats: Double?,
  @SerialName("sek") override val sek: Double?,
  @SerialName("sgd") override val sgd: Double?,
  @SerialName("thb") override val thb: Double?,
  @SerialName("try") override val tryX: Double?,
  @SerialName("twd") override val twd: Double?,
  @SerialName("uah") override val uah: Double?,
  @SerialName("usd") override val usd: Double?,
  @SerialName("vef") override val vef: Double?,
  @SerialName("vnd") override val vnd: Double?,
  @SerialName("xag") override val xag: Double?,
  @SerialName("xau") override val xau: Double?,
  @SerialName("xdr") override val xdr: Double?,
  @SerialName("xlm") override val xlm: Double?,
  @SerialName("xrp") override val xrp: Double?,
  @SerialName("yfi") override val yfi: Double?,
  @SerialName("zar") override val zar: Double?
): ValueInCurrencyDTO
